#!/bin/bash

########options########
log_purge=true
log_purge_days=7
fax_purge=false
fax_purge_days=90
recordings_purge=false
recordings_purge_days=90
vm_purge=false
vm_purge_days=90
cdr_purge=true
cdr_purge_days=90
#######################

#settings
export PGPASSWORD="zzz"
export PGSSLMODE=verify-ca
export PGSSLROOTCERT=/etc/fusionpbx/ca.crt
servernum="nnn"
db_host=127.0.0.1
db_port=26257
db_user=fusionpbx

exec_sql () {
	psql --host=${db_host} --username=${db_user} --port ${db_port} -c "$1"
	#ssh root@${db_host[0]} 'cockroach sql --execute="use fusionpbx;${1}" --certs-dir=/usr/local/cockroach/certs'
}

#set the date
now=$(date +%Y-%m-%d)

#show message to the console
echo "Maintenance Started"

#delete freeswitch logs older 7 days
if [ .$log_purge = ."true" ]; then
	find /var/log/freeswitch/freeswitch.log.* -mtime +${log_purge_days} -exec rm {} \;
fi

#delete faxes
if [ .$fax_purge = ."true" ]; then
	if [ .$servernum = ."1" ]; then
		find /var/lib/freeswitch/storage/fax/*  -name '*.tif' -mtime +${fax_purge_days}  -exec rm {} \;
		find /var/lib/freeswitch/storage/fax/*  -name '*.pdf' -mtime +${fax_purge_days}  -exec rm {} \;
		#delete from the database
		exec_sql "delete from v_fax_files WHERE fax_date < NOW() - INTERVAL '${fax_purge_days}  days'"
		exec_sql "delete from v_fax_logs WHERE fax_date < NOW() - INTERVAL '${fax_purge_days}  days'"
	fi
fi


#delete call recordings
if [ .$recordings_purge = ."true" ]; then
	if [ .$servernum = ."1" ]; then
		find /var/lib/freeswitch/recordings/*/archive/*  -name '*.wav' -mtime +${recordings_purge_days} -exec rm {} \;
		find /var/lib/freeswitch/recordings/*/archive/*  -name '*.mp3' -mtime +${recordings_purge_days} -exec rm {} \;
		exec_sql "delete from v_call_recordings WHERE call_recording_date < NOW() - INTERVAL '${recordings_purge_days} days'"
	fi
fi

#delete voicemail
if [ .$vm_purge = ."true" ]; then
	if [ .$servernum = ."1" ]; then
		find /var/lib/freeswitch/storage/voicemail/default/*  -name 'msg_*.wav' -mtime +${vm_purge_days} -exec rm {} \;
		find /var/lib/freeswitch/storage/voicemail/default/*  -name 'msg_*.mp3' -mtime +${vm_purge_days} -exec rm {} \;
		exec_sql "delete from v_voicemail_messages WHERE to_timestamp(created_epoch) < NOW() - INTERVAL '90 days'"
	fi
fi

#delete call detail records
if [ .$cdr_purge = ."true" ]; then
	exec_sql "delete from v_xml_cdr WHERE start_stamp < NOW() - INTERVAL '${cdr_purge_days} days'"
fi

#completed message
echo "Maintenance Completed";
